apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Release.Name }}
  {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.deploymentSelectorMatchLabels | nindent 6 }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.containerHealthProbePort }}"
        checksum/config: {{ include (print $.Template.BasePath "/query-service-config.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: service-config
          configMap:
            name: {{ .Values.queryServiceConfig.name }}
        - name: log4j-config
          configMap:
            name: {{ .Values.logConfig.name }}
    {{- with .Values.nodeLabels }}
      nodeSelector:
      {{- toYaml . | nindent 8}}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8}}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8}}
    {{- end }}
    {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8}}
    {{- end }}
    {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8}}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "queryservice.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc-port
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
            - name: health-port
              containerPort: {{ .Values.containerHealthProbePort }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: "{{ .Chart.Name }}"
            - name: BOOTSTRAP_CONFIG_URI
              value: "file:///app/resources/configs"
            - name: LOG4J_CONFIGURATION_FILE
              value: "/var/{{ .Chart.Name }}/log/log4j2.properties"
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}
          volumeMounts:
            - name: service-config
              mountPath: /app/resources/configs/{{ .Chart.Name }}/application.conf
              subPath: application.conf
            - name: log4j-config
              mountPath: /var/{{ .Chart.Name }}/log
          livenessProbe:
            periodSeconds: {{ int .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ int .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ int .Values.livenessProbe.timeoutSeconds }}
            httpGet:
              path: /health
              port: {{ .Values.containerHealthProbePort }}
          startupProbe:
            periodSeconds: {{ int .Values.startupProbe.periodSeconds }}
            failureThreshold: {{ int .Values.startupProbe.failureThreshold }}
            timeoutSeconds: {{ int .Values.startupProbe.timeoutSeconds }}
            httpGet:
              path: /health
              port: {{ .Values.containerHealthProbePort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
