apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.queryServiceConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    service.config = {
      tenantColumnName = "{{ .Values.queryServiceConfig.data.tenantColumnName }}"
      attribute.client = {
        host = {{ .Values.queryServiceConfig.data.attributeClient.host }}
        port = {{ .Values.queryServiceConfig.data.attributeClient.port }}
      }
      validation.limit = {
        min = {{ .Values.queryServiceConfig.data.validation.limit.min }}
        max = {{ .Values.queryServiceConfig.data.validation.limit.max }}
        mode = {{ .Values.queryServiceConfig.data.validation.limit.mode }}
      }
      clients = [
        {
          type = zookeeper
          connectionString = "{{ .Values.queryServiceConfig.data.zookeeperConnectionString }}"
        }
        {
          type = postgres
          connectionString = "{{ .Values.queryServiceConfig.data.postgresConnectionString }}"
          user = "{{ .Values.queryServiceConfig.data.postgresUser }}"
          maxConnectionAttempts = "{{ .Values.queryServiceConfig.data.postgresMaxConnectionAttempts }}"
          connectionRetryBackoff = "{{ .Values.queryServiceConfig.data.postgresConnectionRetryBackoff }}"
        }
      ]
      {{- if or .Values.handlers .Values.extraHandlers }}
      queryRequestHandlersConfig = [
      {{- range .Values.handlers }}
        {
{{ tpl . $ | indent 10 }}
        }
      {{- end }}
      {{- range .Values.extraHandlers }}
        {
{{ tpl . $ | indent 10 }}
        }
      {{- end }}
      ]
      {{- end }}
    }