name: build and validate
on:
  push:
    branches:
      - main
  pull_request_target:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_READ_USER }}
          password: ${{ secrets.DOCKERHUB_READ_TOKEN }}
      
      - name: Build with Gradle
        uses: hypertrace/github-actions/gradle@main
        with: 
          args: build dockerBuildImages

      - name: Determine docker tag
        id: tag
        run: echo ::set-output name=tag::$(./gradlew -q printDockerImageDefaultTag | head -1)

      - name: Scan docker image
        uses: azure/container-scan@v0.1
        with:
          image-name: hypertrace/query-service:${{ steps.tag.outputs.tag }}
        env:
          DOCKLE_HOST: "unix:///var/run/docker.sock"
        continue-on-error: true

      - name: Run Trivy vulnerability scanner for ingester
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/hypertrace-ingester
          output-mode: github

      - name: Run Trivy vulnerability scanner for span-normalizer
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/span-normalizer
          output-mode: github

      - name: Run Trivy vulnerability scanner for raw-spans-grouper
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/raw-spans-grouper
          output-mode: github

      - name: Run Trivy vulnerability scanner for trace-enricher
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/hypertrace-trace-enricher
          output-mode: github

      - name: Run Trivy vulnerability scanner for view creator
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/hypertrace-view-creator
          output-mode: github

      - name: Run Trivy vulnerability scanner for view-generator
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/hypertrace-view-generator
          output-mode: github

      - name: Run Trivy vulnerability scanner for metrics generator
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/hypertrace-metrics-generator
          output-mode: github

      - name: Run Trivy vulnerability scanner for metrics processor
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/hypertrace-metrics-processor
          output-mode: github

      - name: Run Trivy vulnerability scanner for metrics exporter
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/hypertrace-metrics-exporter
          output-mode: github

  validate-helm-charts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: validate charts
        uses: hypertrace/github-actions/validate-charts@main
